import React from "react";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import "@/app/globals.css";
import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";

const inter = Roboto({ weight: "400", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark:bg-black dark:text-white">
      <ReduxProvider>
        <body className=" flex flex-col w-full h-full relative">
          <div className="flex-grow p-4 ml-44 w-[calc(100vw-208px)]">
            {children}
          </div>
          <Sidebar />
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
